config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/help'

  resources :administrators
  resources :account_activations, only: [:edit]
  resources :requests
  resources :students

  root 'requests#new'
  get 'tohelp' => 'static_pages#help'
  get 'submit' => 'requests#new'
  get 'adminlogin' => 'sessions#new'
  post 'adminlogin' => 'sessions#create'
  delete 'adminlogout' => 'sessions#destroy'
  get 'requestqueue' => 'requests#index'
  get 'createadmin' => 'administrators#new'
  get 'requests/:id' => 'requests#show', as: :decision
  get 'deciderequest' => 'requests#decide_request'
  get 'thisisretardedlylong/howdidyougethere' => 'administrators#new'
  
  

end

app/views/user_notifier/account_activation.html.erb
<h1>Room Change Notice</h1>

<p>Hello <%= @request.clid%>,</p>

<p>This email is to inform you about a room change request made using your CLID.</p>

<p>The requested building and/or room are the <%=@request.building%> <%=@request.room%>. Click below to confirm:</p>

<%= link_to 'Confirm',edit_account_activation_url(@request.activation_token, clid: @request.clid)%>

app/views/user_notifier/account_activation.text.erb
Hello <%= @request.clid%>,

This email is to inform you about a room change request made using your CLID.

The requested building and/or room are the <%=@request.building%> <%=@request.room%>. Copy the URL below to confirm:

<%= edit_account_activation_url(@request.activation_token, clid: @request.clid)%>

app/views/user_notifier/request_approved.html.erb
<h1>Request Approved</h1>

<p>
   Your room change request has been approved. The room requested is:
</p>

<p><%= @request.building%></p>
<p><%= @request.room%></p>

app/views/user_notifier/request_approved.text.erb
Your room change request has been approved. The room requested is:

<%= @request.building%>
<%= @request.room%>

app/views/user_notifier/request_denied.html.erb
<h1>Request Denied</h1>

<p>
Your room change request has been denied. The room requested is:
</p>

<p><%= @request.building%></p>
<p><%= @request.room%></p>

app/views/user_notifier/request_denied.text.erb
Your room change request has been denied. The room requested is:

<%= @request.building%>
<%= @request.room%>