config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/help'

  resources :administrators
  resources :account_activations, only: [:edit]
  resources :requests
  resources :students

  root 'requests#new'
  get 'tohelp' => 'static_pages#help'
  get 'submit' => 'requests#new'
  get 'adminlogin' => 'sessions#new'
  post 'adminlogin' => 'sessions#create'
  delete 'adminlogout' => 'sessions#destroy'
  get 'requestqueue' => 'requests#index'
  get 'createadmin' => 'administrators#new'
  get 'requests/:id' => 'requests#show', as: :decision
  get 'deciderequest' => 'requests#decide_request'
  get 'thisisretardedlylong/howdidyougethere' => 'administrators#new'
  
  

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessor :activation_token
  before_save {self.clid = clid.downcase}
  before_create :create_activation_digest
  VALID_CLID_REGEX = /\A[a-z]{3}+\d{4}/
  validates :clid, length: {maximum: 7, minimum: 7}, presence: true, uniqueness: {case_sensitive: false}, 
  format: {with: VALID_CLID_REGEX}
  validates :gender, presence: true
  #, format: {with: /\A[mfMF]\z/}
  validates :room, length: {maximum: 4}
  validates :building, presence: true
  
  def activate_request
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end
  
  def send_notification_email
    UserNotifier.account_activation(self).deliver_now!
  end
  
  def send_accept_email
    UserNotifier.request_approved(self).deliver_now!
  end
  
  def send_deny_email
    UserNotifier.request_denied(self).deliver_now!
  end
  
  def remove_request(parameter)
    Request.find(parameter).destroy
  end
  
    def Request.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end
    def create_activation_digest
      self.activation_token = Request.new_token
      self.activation_digest = Request.digest(activation_token)
    end
    
    # Returns a random token.
    def Request.new_token
      SecureRandom.urlsafe_base64
    end
    
    def authenticated?(attribute, token)
      digest = send("#{attribute}_digest")
      return false if digest.nil?
      BCrypt::Password.new(digest).is_password?(token)
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :admin_logged_in, only: [:index,:show, :edit, :update, :destroy]
  

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.paginate(page: params[:page])
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    if @request.save
      @request.send_notification_email
      flash[:info] = 'Confirmation email sent to your school email address.'
      redirect_to root_url
    else
      render 'new'
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    
    @request = Request.find(params[:id])
    if @request.present?
      @request.destroy
    end
    redirect_to requestqueue_url
  end
  
  def decide_request
    @request = Request.find(params[:id])
    if params[:accept]
      @request.send_accept_email
      flash[:success] = 'Request accepted'
    else
      @request.send_deny_email
      flash[:danger] = 'Request denied'
    end
    @request.remove_request(params[:id])
    redirect_to requestqueue_url
  end

  private
    #confirms the admin is logged in
    def admin_logged_in
      unless logged_in?
        flash[:danger] = 'Log in.'
        redirect_to root_url
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:clid, :gender, :building, :room)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<div class="row">
	<div class="col-mid-2">
		<%= form_for(@request) do |f| %>
		  <%= render 'shared/error_messages'%>
		
		  <div class="field">
		    <%= f.label :clid %><br>
		    <%= f.text_field :clid %>
		  </div>
		  <div class="field">
		    <%= f.label :gender %><br>
		    <%= f.label :gender, "Male", :value => "male" %>
		    <%= f.radio_button :gender, "male"%> <br />
		    <%= f.label :gender, "Female", :value => "female" %>
		    <%= f.radio_button :gender, "female"%>
		  </div>
		  <div class="field">
		    <%= f.label :building %><br>
		    <%= f.select :building, options_for_select(%w(Conference\ Center Harris\ Hall Legacy\ Park Baker\ Hall Bonin\ Hall 
		    	Coronna\ Hall Huger\ Hall)) %>
		  </div>
		  <div class="field">
		    <%= f.label :room %><br>
		    <%= f.text_field :room %>
		  </div>
		  <div class="actions">
		    <%= f.submit "Send", class: "btn btn-primary" %>
		  </div>
		<% end %>
	</div>
</div>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<% provide(:title,"Request Queue")%>
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table style="width: 100%">
  <thead>
    <tr>
      <th>CLID</th>
      <th>Gender</th>
      <th>Current Building</th>
      <th>Current Room</th>
      <th>Requested Building</th>
      <th>Requested Room</th>
      <th colspan="20"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
		<% if request.activated? %>
			<%= @student = Student.find_by(clid: request.clid)%>
			<tr>
	        <td><%= request.clid %></td>
	        <td><%= request.gender %></td>
	        <% if !@student.nil? %>
	        	<td><%= @student.building%></td>
	        	<td><%= @student.roomid %></td>
	        <!-- If student is nil, display nothing to avoid errors. -->
	        <%else %>
	        	<td></td>
	        	<td></td>
	        <%end%>
	        <td><%= request.building %></td>
	        <td><%= request.room %></td>
	        <td><%= link_to 'Accept', deciderequest_path(request, :accept => true, :id => request.id)  %></td>
			<td><%= link_to 'Deny', deciderequest_path(request, :accept => false, :id => request.id) %></td>
	      </tr>      
	      <%end %>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>
<br>
<%= link_to 'New Administrator', new_administrator_path,class:"btn" %>

app/views/requests/new.html.erb
<% provide(:title,"Submit Request")%>

<h1>Submit Request</h1>
<div class="center jumbotron">
	<%= render 'form' %>
</div>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>CLID:</strong>
  <%= @request.clid %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @request.gender %>
</p>

<p>
  <strong>Current Building:</strong>
  <%=  %>
</p>

<p>
  <strong>Current Room:</strong>
  <%=  %>
</p>

<p>
  <strong>Chosen Building:</strong>
  <%= @request.building %>
</p>

<p>
  <strong>Chosen Room:</strong>
  <%= @request.room %>
</p>

<%= link_to 'Accept', accept_request_path(@request)  %> |
<%= link_to 'Deny', deny_request_path(@request) %> |
<%= link_to 'Back', requests_path %>