config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/help'

  resources :administrators
  resources :account_activations, only: [:edit]
  resources :requests
  resources :students

  root 'requests#new'
  get 'tohelp' => 'static_pages#help'
  get 'submit' => 'requests#new'
  get 'adminlogin' => 'sessions#new'
  post 'adminlogin' => 'sessions#create'
  delete 'adminlogout' => 'sessions#destroy'
  get 'requestqueue' => 'requests#index'
  get 'createadmin' => 'administrators#new'
  get 'requests/:id' => 'requests#show', as: :decision
  get 'deciderequest' => 'requests#decide_request'
  get 'thisisretardedlylong/howdidyougethere' => 'administrators#new'
  
  

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  before_save {self.username = username.downcase}
  validates :username, presence: true, uniqueness: {case_sensitive:false}
  validates :password, presence: true, length: {minimum: 8}
  
  has_secure_password
  def Administrator.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def Administrator.new_token
    SecureRandom.urlsafe_base64
  end
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :admin_logged_in, only: [:index,:show, :edit, :update, :destroy,:new]

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
    @administrator = Administrator.find(params[:id])
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)
    if @administrator.save
      flash[:success] = 'New administrator created.'
      redirect_to requestqueue_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #confirms the admin is logged in
    def admin_logged_in
      unless logged_in?
        flash[:danger] = 'Log in.'
        redirect_to root_url
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params.require(:administrator).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<div class="row">
	<div class="col-mid-2">
		<%= form_for(@administrator) do |f| %>
		  <% if @administrator.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>
		
		      <ul>
		      <% @administrator.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		
		  <div class="field">
		    <%= f.label :username %><br>
		    <%= f.text_field :username %>
		  </div>
		  <div class="field">
		    <%= f.label :password %><br>
		    <%= f.password_field :password %>
		  </div>
		  <div class="field">
		    <%= f.label :password_confirmation %><br>
		    <%= f.password_field :password_confirmation %>
		  </div>
		  <div class="actions">
		    <%= f.submit "Create", class: "btn btn-primary" %>
		  </div>
		<% end %>
	</div>
</div>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<% provide(:title,"Administrators")%>

<h1>Listing Administrators</h1>

<table style="width: 100%">
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.username %></td>
        <td><%= administrator.password %></td>
        <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path, class:"btn btn-primary" %>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<div class="center jumbotron"><%= render 'form' %></div>

<%= link_to 'Back', requests_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @administrator.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @administrator.password %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>