config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/help'

  resources :administrators
  resources :account_activations, only: [:edit]
  resources :requests
  resources :students

  root 'requests#new'
  get 'tohelp' => 'static_pages#help'
  get 'submit' => 'requests#new'
  get 'adminlogin' => 'sessions#new'
  post 'adminlogin' => 'sessions#create'
  delete 'adminlogout' => 'sessions#destroy'
  get 'requestqueue' => 'requests#index'
  get 'createadmin' => 'administrators#new'
  get 'requests/:id' => 'requests#show', as: :decision
  get 'deciderequest' => 'requests#decide_request'
  get 'thisisretardedlylong/howdidyougethere' => 'administrators#new'
  
  

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<%= link_to "Housing", 'http://housing.louisiana.edu', id: "logo" %>
		<div class="container">
			<nav>
				<ul class="nav navbar-nav pull-right">
					<li class="divider"></li>
					<% if logged_in? %>
						<li><%= link_to 'Requests', requests_path%></li>
						<li><%= link_to "Create Admin", createadmin_path%></li>
						<li><%= link_to "Log Out", adminlogout_path, method: "delete" %></li>
					<% else%>
						<li><%= link_to "Submit Request",submit_path%></li>
						<li><%= link_to "Log In", adminlogin_path%></li>
					<% end%>
					<li><%= link_to "Help",tohelp_path %></li>
				</ul>
			</nav>
		</div>
		
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
</head>
<body>
	<%= render 'layouts/header'%>
	<% flash.each do |message_type, message| %>
  			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
	<div class="container">
		<%= yield %>
	
	<%= render 'layouts/footer' %>
    <!--<%= debug(params) if Rails.env.development? %>-->

</div>


</body>
</html>